### ISSUE TITLE
ModuleNotFoundError: No module named 'PySimpleGUI'

### ISSUE THREAD

**Issue by siikdUde** [dunneja/Nagini#1]
```
base ❯ cd Nagini

~/Nagini main
base ❯ pip3 install -r requirements.txt
Collecting clipboard (from -r requirements.txt (line 1))
  Downloading clipboard-0.0.4.tar.gz (1.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PySimpleGUI (from -r requirements.txt (line 2))
  Downloading PySimpleGUI-5.0.3-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (2.31.0)
Collecting pysnmp (from -r requirements.txt (line 4))
  Downloading pysnmp-4.4.12-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: urllib3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (2.1.0)
Collecting pyperclip>=1.3 (from clipboard->-r requirements.txt (line 1))
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rsa (from PySimpleGUI->-r requirements.txt (line 2))
  Downloading rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->-r requirements.txt (line 3)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->-r requirements.txt (line 3)) (3.6)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->-r requirements.txt (line 3)) (2023.11.17)
Collecting pysmi (from pysnmp->-r requirements.txt (line 4))
  Downloading pysmi-0.3.4-py2.py3-none-any.whl.metadata (1.6 kB)
Collecting pycryptodomex (from pysnmp->-r requirements.txt (line 4))
  Downloading pycryptodomex-3.20.0-cp35-abi3-macosx_10_9_universal2.whl.metadata (3.4 kB)
Collecting pyasn1>=0.2.3 (from pysnmp->-r requirements.txt (line 4))
  Downloading pyasn1-0.5.1-py2.py3-none-any.whl.metadata (8.6 kB)
Collecting ply (from pysmi->pysnmp->-r requirements.txt (line 4))
  Downloading ply-3.11-py2.py3-none-any.whl.metadata (844 bytes)
Downloading PySimpleGUI-5.0.3-py3-none-any.whl (993 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 993.3/993.3 kB 143.5 kB/s eta 0:00:00
Downloading pysnmp-4.4.12-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 99.2 kB/s eta 0:00:00
Downloading pyasn1-0.5.1-py2.py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.9/84.9 kB 126.4 kB/s eta 0:00:00
Downloading pycryptodomex-3.20.0-cp35-abi3-macosx_10_9_universal2.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 257.9 kB/s eta 0:00:00
Downloading pysmi-0.3.4-py2.py3-none-any.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.0/80.0 kB 135.1 kB/s eta 0:00:00
Downloading rsa-4.9-py3-none-any.whl (34 kB)
Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 110.9 kB/s eta 0:00:00
Building wheels for collected packages: clipboard, pyperclip
  Building wheel for clipboard (pyproject.toml) ... done
  Created wheel for clipboard: filename=clipboard-0.0.4-py3-none-any.whl size=1846 sha256=6bfc7f99456197d71ea3d92ca22541f4546e0983c90b7ca33264fc9374216126
  Stored in directory: /Users/deanmbp/Library/Caches/pip/wheels/04/b3/04/2621ebdf512537108eb48427ce3c1f5ffa6a82e51ccca0f0e1
  Building wheel for pyperclip (pyproject.toml) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11124 sha256=a60b651f6c8c80e7bde7481831355d793811e3c47dbf5af4154deec51dd75470
  Stored in directory: /Users/deanmbp/Library/Caches/pip/wheels/b7/e1/45/ce0a91b8cdfed625867580ed90242e4581c4995f69fd062e07
Successfully built clipboard pyperclip
Installing collected packages: pyperclip, ply, pysmi, pycryptodomex, pyasn1, clipboard, rsa, pysnmp, PySimpleGUI
Successfully installed PySimpleGUI-5.0.3 clipboard-0.0.4 ply-3.11 pyasn1-0.5.1 pycryptodomex-3.20.0 pyperclip-1.8.2 pysmi-0.3.4 pysnmp-4.4.12 rsa-4.9

~/Nagini main 37s
base ❯ python -m  nagini
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/x/Nagini/nagini.py", line 10, in <module>
    from gui.nagini_main import prn_tool_gui
  File "/Users/x/Nagini/gui/__init__.py", line 9, in <module>
    from gui import nagini_csv_view
  File "/Users/x/Nagini/gui/nagini_csv_view.py", line 13, in <module>
    import PySimpleGUI as sg
ModuleNotFoundError: No module named 'PySimpleGUI'

```

**Comment by dunneja** [comment]
i've successfully setup and ran the tool from Python 3.11.x from the following steps;

1.  git clone https://github.com/dunneja/Nagini
2.  cd Nagini
3. python -m venv venv
4. activate the venv & update pip
5. pip3 install -r requirements.txt 
6. python -m nagini
7. GUI tool starts ok.

PySimpleGUI is now no longer completely free.. so you get prompted to start a trial. Once you complete the steps, restart the Nagini project and the GUI tool opens with a banner along the bottom stating PySimpleGUI is running in trial mode. 

I tried the above steps for Python 3.12.x but the pysnmp module uses a deprecated package that has been removed in python 3.12.x (asyncore rather than the newer asyncio.) since Pysnmp hasn't been released since 2019, i doubt this will get fixed and is an upstream issue anyway.

Since i don't actually need this project anymore, i won't be looking into the pysnmp package deprecation issue, so this project will only work with Python 3.11.x once you deal with the PySimpleGui registration stuff.
